/**
 * Created by VladimirVS on 28.01.2015.
 */

// времена глаголов
var test1Data = [["Ты полюбишь?","Will you love?"],
    ["Я полюблю","I will love"],
    ["Она не полюбит","She will not love"],
    ["Они любят?","Do they love?"],
    ["Джон любит?","Does John love?"],
    ["Он любит","He loves"],
    ["Они любят","They love"],
    ["Мы любим","We love"],
    ["Он не любит","He doesn't love"],
    ["Мы любили?","Did we love?"],
    ["Ты любила","You loved"],
    ["Она не любила","She didn't love"],
    ["Они будут знать?","Will they know?"],
    ["Она знает?","Does she know?"],
    ["Он знает","He knows"],
    ["Я знал","I knew"],
    ["Мы не знали","We didn't know"],
    ["Она будет гулять?","Will she walk?"],
    ["Они не будут гулять","They will not walk"],
    ["Я гуляю","I walk"],
    ["Ты гулял?","Did you walk?"],
    ["Он не гулял","He didn't walk"],
    ["Они будут работать?","Will they work?"],
    ["Она работает?","Does she work?"],
    ["Я работаю","I work"],
    ["Он работал","He worked"],
    ["Мы не работали","We didn't work"]];

// слова
var test2Data = [["балкон","balcony"],
    ["беременная","pregnant (прэгнант)"],
    ["беспокоить","disturb (дистОб)"],
    ["бесполезный","useless (юзлесс)"],
    ["благодарный","grateful (грэйтфул)"],
    ["близлежащий","nearby (небай)"],
    ["блюдо","dish"],
    ["боль","pain"],
    ["больной","ill"],
    ["больной","sick"],
    ["борода","beard"],
    ["бояться","be afraid"],
    ["бриться","shave (шейв)"],
    ["вдохновлять","inspire (инспАе)"],
    ["везде","everywhere"],
    ["вены","veins"],
    ["верить","believe"],
    ["вероятный","likely"],
    ["весна","spring"],
    ["вилка","fork"],
    ["вкусный","delicious"],
    ["вкусный","tasty"],
    ["влажный","wet"],
    ["влияние","impact"],
    ["влиять","affect"],
    ["влюбленный","in love"],
    ["вместо","instead (инстЭд)"],
    ["внутренний","interior (интериа)"],
    ["возбуждать","excite"],
    ["война","war (во)"],
    ["войти","enter"],
    ["волноваться","worry"],
    ["волосы","hair (хэа)"],
    ["воображать","imagine"],
    ["воровать","steal"],
    ["восприятие","perception"],
    ["впечатление","impression"],
    ["впитывать","absorb (абзОб)"],
    ["враг","enemy"],
    ["всегда","always"],
    ["встречать","meet"],
    ["вторник","Tuesday (тьюсдэй)"],
    ["всё","everything"],
    ["всякий","everybody"],
    ["высокий","tall (тол)"],
    ["вытирать","wipe"],
    ["галстук","tie (тай)"],
    ["где","where"],
    ["где-нибудь","somewhere"],
    ["глаголы","verbs"],
    ["глаза","eyes (айс)"],
    ["голова","head (хэд)"],
    ["голодный","hungry"],
    ["гора","mountain (маунтин)"],
    ["гордый","proud"],
    ["горло","throat (фроойт)"],
    ["гость","guest (гэст)"],
    ["греть","heat (хит)"],
    ["громкий","loud (лауд)"],
    ["даже","even"],
    ["добрый","kind (каинд)"],
    ["доверять","trust (траст)"],
    ["дождливо","raining"],
    ["доказывать","prove (прув)"],
    ["доля","share (шэа)"],
    ["допускать","admit"],
    ["достаточно","enough (эноф)"],
    ["достигать","reach"],
    ["достижения","achievements"],
    ["доступно","available (эвЭйлебэл)"],
    ["доход","income"],
    ["дуть","blow"],
    ["душа","soul"],
    ["душно","stuffy"],
    ["дышать","breathe (бриф)"],
    ["дядя","uncle"],
    ["его","him"],
    ["еда","meal (мил)"],
    ["ее","her"],
    ["женщины","woman (вимен)"],
    ["жертва","victim"],
    ["жить","live"],
    ["забота","care (кее)"],
    ["завидовать","envy"],
    ["завтрак","breakfast (брэкфэст)"],
    ["заимствовать","borrow"],
    ["закон","law (лёу)"],
    ["замечание","remark"],
    ["запас","reserve"],
    ["запах","smell"],
    ["зарабатывать","earn (эн)"],
    ["зарубежный","foreign (форэн)"],
    ["затраты","expenses"],
    ["защищать","defend"],
    ["здоровье","health (хэлф)"],
    ["злой","evil (ивил)"],
    ["зубы","teeth"],
    ["избавляться","get rid"],
    ["избегать","avoid (эвОйд)"],
    ["измерять","measure (межа)"],
    ["изобретать","invent"],
    ["изучать","study"],
    ["иногда","sometimes"],
    ["искусство","art"],
    ["их","them"],
    ["как","how"],
    ["казаться","seem"],
    ["капуста","cabbage"],
    ["квартал","quarter (кууте)"],
    ["квартира","flat (флат)"],
    ["кепка","cap"],
    ["кипятить","boil"],
    ["кислый","sour (сауа)"],
    ["когда","when"],
    ["когда-либо","ever"],
    ["кого","whom"],
    ["конкретный","particular (патикила)"],
    ["коньки","skates"],
    ["кормить","feed"],
    ["кошелек","purse"],
    ["красивый","pretty (прити)"],
    ["краткосрочный","short-term"],
    ["креветка","shrimp"],
    ["кресло","armchair"],
    ["кричать","shout (шаут)"],
    ["кровать","bed"],
    ["кроме","except (иксЭпт)"],
    ["крыша","roof (рейф)"],
    ["кто","who"],
    ["кто-нибудь","somebody"],
    ["куртка","jacket (джакет)"],
    ["кухня","kitchen (кичен)"],
    ["лгать","lie (лаай)"],
    ["лед","ice"],
    ["лежать","lay"],
    ["лежать","lie"],
    ["лес","forest"],
    ["лестница","stairs"],
    ["лето","summer"],
    ["листва","foliage"],
    ["лицо","face"],
    ["ловушка","trap"],
    ["ложка","spoon"],
    ["мало","few (фью)"],
    ["матч","match (мач)"],
    ["мебель","furniture (фэнича)"],
    ["мнение","opinion (опинен)"],
    ["мода","fashion"],
    ["молния","zipper"],
    ["молодой","young (ян)"],
    ["море","sea (сей)"],
    ["морковь","carrots"],
    ["мудрость","wisdom"],
    ["мудрый","wise (вайс)"],
    ["муж","husband (хазбэнд)"],
    ["ненормальный","crazy"],
    ["навсегда","forever"],
    ["над","over (оувэ)"],
    ["награда","reward"],
    ["наказать","punish"],
    ["накладные расходы","overheads"],
    ["налог","tax"],
    ["напоминать","remind (ремАйнд)"],
    ["нарушать","violate (вАйлет)"],
    ["нас","us"],
    ["настроение","mood"],
    ["невинный","innocent"],
    ["ненавидеть","hate"],
    ["необходимый","necessary (нэсэссАри)"],
    ["необходимый","required (рекваед)"],
    ["неприятный","unpleasant (анпЭзент)"],
    ["нести","carry"],
    ["нигде","nowhere"],
    ["никогда","never"],
    ["никто","nobody"],
    ["ничего","nothing"],
    ["нечестный","unfair (анфэа)"],
    ["нога","leg"],
    ["ноги","feet"],
    ["ногти","nails (нэилс)"],
    ["нож","knife"],
    ["нос","nose (нойс)"],
    ["носить","wear (вэа)"],
    ["носки","socks"],
    ["обвинять","blame"],
    ["обед","lunch"],
    ["обижать","offend"],
    ["обманывать","cheat"],
    ["обожать","adore"],
    ["обсуждение","discussion (дискАшн)"],
    ["обувь","shoes (шуз)"],
    ["обычно","usually (южили)"],
    ["объяснять","explain"],
    ["обязанность","duty"],
    ["огурец","cucumber"],
    ["одежда","clothes (клоувз)"],
    ["однажды","once (ванс)"],
    ["ожидать","expect"],
    ["опыт","experience"],
    ["осень","autumn (отэм)"],
    ["оставаться","stay (стэй)"],
    ["ответственный","responsible"],
    ["отвлекать","distract"],
    ["отвлекать","divert"],
    ["отдых","rest"],
    ["отжимание","push-up"],
    ["отказывать","refuse"],
    ["отлично","excellent"],
    ["отношения","relations"],
    ["официант","waiter"],
    ["падать","drop"],
    ["падать","fall (фол)"],
    ["парень","guy (гай)"],
    ["перец","pepper"],
    ["перчатки","gloves"],
    ["песня","song (сон)"],
    ["петь","sing (син)"],
    ["пироженное","pie (пай)"],
    ["плакать","cry"],
    ["платье","dress"],
    ["племянник","nephew (нефье)"],
    ["плечо","shoulder"],
    ["плита","stove"],
    ["поведение","behavior (бэхЭйвиэ)"],
    ["поворачивать","turn"],
    ["погода","weather (вэта)"],
    ["подготовить","prepare (припЭ)"],
    ["подстраховаться","insure (иншо)"],
    ["подтягивание","pull-up"],
    ["подушка","pillow"],
    ["подъезд","porch (пооч)"],
    ["поезд","train (трэйн)"],
    ["позволить","afford (эфОд)"],
    ["поздравлять","congratulate (кэнгрАчилейт)"],
    ["позор","shame"],
    ["положить","put"],
    ["поощрять","encourage (инкОрэдж)"],
    ["поставлять","supply (сэплай)"],
    ["потребитель","consumer"],
    ["потребление","consumption"],
    ["почему","why"],
    ["почти","almost"],
    ["появляться","appear"],
    ["праздновать","celebrate (селебрЭйт)"],
    ["предмет","item (айтэм)"],
    ["предполагать","assume"],
    ["предполагать","suppose"],
    ["предпочитать","prefer (прифЕ)"],
    ["представлять","represent"],
    ["претензия","claim (клэйм)"],
    ["прибывать","arrive (эрАйв)"],
    ["привлекательный","cute"],
    ["привозить","bring"],
    ["привычки","habits"],
    ["приглашать","invite"],
    ["признавать","admit"],
    ["прилагательные","adjectives"],
    ["приносить","bring"],
    ["притворяться","pretend (притЕнд)"],
    ["приходить","come (кам)"],
    ["причина","reason (ризэн)"],
    ["прямо","straight (стрэйт)"],
    ["провожать","see off"],
    ["продолжать","continue (кэнтИне)"],
    ["проснуться","wake up"],
    ["путешествовать","travel"],
    ["публика","audience (одиенс)"],
    ["пятница","Friday (фрайдэй)"],
    ["работодатель","employer (эмплОя)"],
    ["радостный","glad (глаад)"],
    ["раздеваться","undress"],
    ["раздражающий","annoying"],
    ["разминка","warm up"],
    ["разнообразие","diversity"],
    ["разочаровать","disappoint (дизэпОинт)"],
    ["разрешать","allow (элАу)"],
    ["раковина","sink"],
    ["ранний","early"],
    ["рассматривать","consider (консида)"],
    ["расстроенный","upset"],
    ["редко","seldom"],
    ["рекламировать","advertise (адветайс)"],
    ["ремень","belt"],
    ["ремесло","craft"],
    ["решать","decide (дисАйд)"],
    ["родственники","relatives (релятивс)"],
    ["рубашка","shirt (шёт)"],
    ["ругать","scold"],
    ["рука","arm"],
    ["рука","hand (ханд)"],
    ["сахар","sugar (шугэ)"],
    ["святой","holy"],
    ["сердитый","angry"],
    ["сердце","heart (хат)"],
    ["сзади","behind"],
    ["сидеть","sit"],
    ["скамейка","bench"],
    ["скользкий","slippy"],
    ["скромный","modest"],
    ["скучный","boring"],
    ["сладкий","sweet"],
    ["слабый","weak"],
    ["слышать","hear (хиа)"],
    ["смелый","bold"],
    ["смех","laugh (лаф)"],
    ["смысл","sense"],
    ["снабжать","supply (сэплай)"],
    ["снег","snow"],
    ["собственный","own (оун)"],
    ["сожалеть","regret"],
    ["соль","salt (солт)"],
    ["сомнение","doubt (даут)"],
    ["сосед","neighbour (нэйба)"],
    ["сотрудник","employee (эмплОи)"],
    ["спокойный","calm (кам)"],
    ["сравнить","compare (кэмпЭа)"],
    ["среда","Wednesday (вэнсдэй)"],
    ["среди","among (эмОн)"],
    ["срочный","urgent (оджент)"],
    ["стакан","glass"],
    ["становиться","became"],
    ["стесняться","hesitate (хэзитэйт)"],
    ["сторона","side"],
    ["страсть","passion"],
    ["стул","chair (чэа)"],
    ["ступеньки","stairs"],
    ["стыд","shame"],
    ["суд","court"],
    ["суетиться","fuss (фас)"],
    ["сумка","bag (баг)"],
    ["сухой","dry"],
    ["существительные","nouns"],
    ["счастливый","happy"],
    ["счастливый","lucky"],
    ["сыр","cheese (чиз)"],
    ["сюжет","plot"],
    ["тапки","slippers"],
    ["тарелка","plate"],
    ["тетя","aunt (аант)"],
    ["тихий","quiet (квает)"],
    ["толкать","push"],
    ["толпа","crowd (крауд)"],
    ["толстый","fat"],
    ["точно","exactly"],
    ["точный","precise"],
    ["тянуть","pull"],
    ["уважение","respect (риспЭкт)"],
    ["уверенный","confident"],
    ["угадывать","guess (гес)"],
    ["удовольствие","pleasure (плежа)"],
    ["уже","already (олрЭди)"],
    ["ужин","dinner"],
    ["узкий","narrow"],
    ["умирать","die (дай)"],
    ["умный","clever"],
    ["упомянутый","mentioned (меншед)"],
    ["усилие","effort"],
    ["условия","condition (кэндЫшэн)"],
    ["успех","success (сыксЭс)"],
    ["уставший","tired (тайад)"],
    ["ухо","ear"],
    ["участвовать","involve (инвАлв)"],
    ["участник","participant"],
    ["ученый","scientist (саентист)"],
    ["футболка","tee-shirt"],
    ["хвалить","praise (прэйс)"],
    ["холм","hill"],
    ["художник","painter (пэйньта)"],
    ["худой","skinny"],
    ["хуже","worse (вос)"],
    ["цветы","flowers (флауес)"],
    ["чай","tea (ти)"],
    ["чайник","kettle"],
    ["час","hour (ауэ)"],
    ["часто","often (офэн)"],
    ["частота","frequency (фрикунсей)"],
    ["чашка","cup (кап)"],
    ["честный","honest"],
    ["четверг","Thursday (фёсдэй)"],
    ["что","what"],
    ["что-нибудь","something"],
    ["чувствовать","feel"],
    ["чья","whose"],
    ["шапка","cap"],
    ["шарф","scarf (скааф)"],
    ["школа","school (скул)"],
    ["штаны","pants"],
    ["электричество","electricity"],
    ["юбка","skirt (скёт)"],
    ["юг","south (сауф)"],
    ["яркий","bright"]];

// неправильные глаголы
var test3Data = [["be","was, were || been"],
    ["begin","began (бегян) || begun (беган)"],
    ["break","broke || broken"],
    ["build","built"],
    ["buy","bought"],
    ["choose","chose || chosen"],
    ["come","came || come"],
    ["cost","cost"],
    ["cut","cut"],
    ["do","did || done"],
    ["draw","drew || drawn"],
    ["drink","drank || drunk"],
    ["drive","drove || driven"],
    ["eat","ate || eaten"],
    ["fall","fell || fallen"],
    ["feed","fed"],
    ["feel","felt"],
    ["find","found"],
    ["forget","forgot || forgotten"],
    ["forgive","forgave || forgiven"],
    ["get","got"],
    ["give","gave || given"],
    ["go","went || gone"],
    ["grow","grew (грэйв) || grown"],
    ["have","had"],
    ["hide (хайд)","hid (хид) || hidden"],
    ["hold","held"],
    ["keep","kept"],
    ["know","knew (нью) || known"],
    ["leave","left"],
    ["lend","lent"],
    ["lose (луз)","lost"],
    ["make","made"],
    ["meet","met"],
    ["pay","paid"],
    ["put","put"],
    ["read","read (рэд)"],
    ["run","ran || run"],
    ["say","said"],
    ["see","saw (соу) || seen"],
    ["sell","sold"],
    ["send","sent"],
    ["set","set"],
    ["sit","sat"],
    ["sleep","slept"],
    ["speak","spoke || spoken"],
    ["spend","spent"],
    ["stand","stood"],
    ["steal","stole || stolen"],
    ["take","took || taken"],
    ["teach","taught (тот)"],
    ["tell","told"],
    ["think","thought (фёт)"],
    ["understand","understood"],
    ["win","won"],
    ["write","wrote || written"]];

// времена to be
var test4Data = [["Будет он быстрым?","Will he be fast?"],
    ["Будет он хорошим?","Will he be good?"],
    ["Они будут быстрыми","They will be fast"],
    ["Они будут старыми","They will be old"],
    ["Хелен не будет толстой","Helen will not be fat"],
    ["Это не будет здесь","It will not be here"],
    ["Это не будет зеленым","It will not be green"],
    ["Она беременная?","Is she pregnant?"],
    ["Она толстая?","Is she fat?"],
    ["Мы быстрые","We are fast"],
    ["Мы голодные","We are hungry"],
    ["Я не голодный","I am not hungry"],
    ["Я не молодой","I am not young"],
    ["Мы были быстрыми?","Were we fast?"],
    ["Ты был спокойным?","Were you calm?"],
    ["Ты был толстым?","Were you fat?"],
    ["Ты был здесь","You were here"],
    ["Ты был молодым","You were young"],
    ["Хелен была быстрой","Helen was fast"],
    ["Она не была толстой","She was not fat"],
    ["Она не была спокойной","She was not calm"],
    ["Они не были здесь","They weren't here"]];

// выражения
var test5Data = [["а то ...","or else ..."],
    ["без десяти девять","ten to nine"],
    ["билет в два конца","round trip ticket"],
    ["билет в один конец","one way ticket"],
    ["будь осторожен","be careful"],
    ["быть похожим","look like"],
    ["в одно и тоже время","at the same time"],
    ["воспользоваться чем-то","take advantage of"],
    ["воспользуйся шансом","take a chance"],
    ["все равно","all the same"],
    ["вспоминать друг друга","remember each other"],
    ["всякое бывает","things happen"],
    ["вы возражаете если ...","do you mind if ..."],
    ["двадцать минут девятого","twenty past eight"],
    ["для того, чтобы","in order to"],
    ["друг без друга","without each other"],
    ["и т.д.","etc. (эт сэтера)"],
    ["как мне добраться до ...","how can I get to ..."],
    ["как насчет","what about"],
    ["как я уже говорил","as I said before"],
    ["мне все равно","i don't care"],
    ["на втором этаже","on the second floor"],
    ["надо всегда помнить","one should always remember"],
    ["напротив почты","across from the post office"],
    ["не стесняйтесь спросить","feel free to ask"],
    ["не уверен","i’m not sure (ай эм нот шо)"],
    ["ничего страшного","never mind"],
    ["ни за что","no way"],
    ["о вкусах не спорят","tastes differ (тэйстс диффа)"],
    ["подойди сюда","come here"],
    ["поторопись","hurry up!"],
    ["Пошли!","Let’s go!"],
    ["пошли мне SMS","text me"],
    ["прежде всего","first of all"],
    ["пятнадцать минут ходьбы","fifteen minutes walk"],
    ["сдать экзамен","pass the exam"],
    ["сколько времени займет ...","how long does it take ..."],
    ["следуйте за мной","follow me"],
    ["спроси что-нибудь полегче","ask me another"],
    ["такой как","such as (соч эс)"],
    ["теория заговора","conspiracy theory (конспираси сиэри)"],
    ["угощайся пивом","have a beer"],
    ["Хорошего дня!","Have a nice day!"],
    ["чем больше ..., тем меньше ...","the more ... the less ..."],
    ["через 30 минут","in 30 minutes"],
    ["что-нибудь еще","anything else"],
    ["это зависит от","it depends on"],
    ["это звучит как","it sounds like"],
    ["это можно сделать","one can do it"],
    ["я бы хотел ...","i would like ..."],
    ["я готовлюсь","i'm getting ready"],
    ["я ищу ...","i'm looking for ..."],
    ["я собираюсь ...","i am going to ..."],
    ["я сыт","i'm full"]];

// предложения
var test6Data = [["Боюсь, что я не смогу прийти.","I'm afraid I can't come."],
    ["Было бы лучше, если вы их прочитали.","It would be better if you read them."],
    ["Вам нравится работать в больнице?","Do you like to work in the hospital?"],
    ["Вы все еще живете в Австралии?","Do you still live in Australia?"],
    ["В каком смысле?","In what sense?"],
    ["В понедельник я выгляжу хуже чем обычно.","On Monday I look worse than usual."],
    ["В следующий вторник я поеду в Москву.","Next Tuesday I will go to Moscow."],
    ["В чем еще мы нуждаемся?","What else do we need?"],
    ["Возьми что-нибудь еще.","Take something else."],
    ["Входите и присаживайтесь.","Come in and sit down."],
    ["Где-то я его видел.","I saw him somewhere."],
    ["Давайте воспользуемся хорошей погодой.","Let's take advantage of the fine weather."],
    ["Директор подал в отставку.","The director has resigned."],
    ["Для кого ты это делаешь?","Who do you do it for?"],
    ["Дом будет построен.","The house will be built."],
    ["Его видят.","He is seen."],
    ["Ее офис совсем рядом, поэтому она всегда ходит пешком.","Her office is quite near, so she always walks."],
    ["Если ты поможешь мне, ты станешь моим другом.","If you help me you will be my friend."],
    ["Заберет ли он меня?","Will he take me away?"],
    ["Зачем они говорят это?","Why do they speak it?"],
    ["Иногда он работает до 9.","Sometimes he works until nine."],
    ["Какой предпочитаешь?","Which one do you prefer?"],
    ["Как далеко отсюда твой офис?","How far from here is your office?"],
    ["Как называется компания, на которую ты работаешь?","What's the name of the company you work for?"],
    ["Как она узнала их?","How did she know them?"],
    ["Как ты проводишь свои вечера?","How do you spend your evenings?"],
    ["Как ты узнал меня?","How did you know me?"],
    ["Кем ты работаешь в офисе?","What sort of work do you do in the office?"],
    ["Когда закончите это, ответьте на вопросы.","When you have finished it, answer the questions."],
    ["Когда он придет, скажи ему, что я хочу его увидеть.","When he comes, tell him I want to see him."],
    ["Когда ты придешь домой?","When will you come home?"],
    ["Когда ты ходишь на работу?","When do you go to work?"],
    ["Когда ты чувствуешь себя лучше?","When do you feel better?"],
    ["Когда это произошло?","When did this happen?"],
    ["Кого видел ты?","Who did you see?"],
    ["Который ты хочешь?","Which one do you want?"],
    ["Кто был здесь?","Who was here?"],
    ["Кто-нибудь еще подойдет?","Is anyone else coming?"],
    ["Кто послал это письмо?","Who sent this letter?"],
    ["Магазин закрывается в шесть часов.","The shop closes at six o'clock."],
    ["Меня не будет до июня.","I’ll be away until June."],
    ["Мне двадцать три.","I'm twenty three."],
    ["Много ли времени займет написание книги?","How long will it take to write a book?"],
    ["Можешь вместо этого прийти в пятницу.","You can come on Friday instead."],
    ["Можно выйти?","Can I go out?"],
    ["Можно мне одолжить немного денег?","Can I borrow some money?"],
    ["Мой брат ложится спать в девять вечера.","My brother goes to sleep at nine in the evening."],
    ["Могу ли я оставить сообщение?","Can I leave a message?"],
    ["Моя жена на 2 года моложе меня.","My wife is two years younger than I am."],
    ["Мы будем там примерно через час.","We'll be there in about an hour."],
    ["Мы не можем себе позволить новую машину в этом году.","We can't afford a new car this year."],
    ["Мы поужинали десять минут назад.","We had dinner ten minutes ago."],
    ["Мы собираемся в кино через неделю.","We are going to the cinema in a week."],
    ["Мы уже знаем некоторые из них.","We already know some of them."],
    ["На кухне кто-то есть.","Someone is in the kitchen."],
    ["На сколько муж старше вас?","How much older is your husband than you?"],
    ["На улице холодно?","Is it cold outside?"],
    ["Надеюсь, что ты ему ничего не дал.","I hope you gave him nothing."],
    ["Наш телефон поломался и мы не могли отвечать ни на какие звонки.","Our phone was broken and we couldn't receive any calls."],
    ["Но это занимает много времени, так как информацию сложно найти.","But it's taking a long time because the information is difficult to find."],
    ["Он все еще работает?","Is he still working?"],
    ["Он думает, что мы не хотим идти.","He thinks we don't want to go."],
    ["Он извинялся, что не мог мне помочь.","He was sorry he couldn't help me."],
    ["Он написал уже свою книгу?","Has he written his book yet?"],
    ["Он не говорит со мной.","He doesn't speak to me."],
    ["Он не надеется на тебя.","He doesn't hope for you."],
    ["Он никогда не видел снега.","He has never seen the snow."],
    ["Он пришёл чтобы поговорить.","He came to speak."],
    ["Он работает меньше, чем его отец, но больше зарабатывает.","Не works less than his father but is paid more."],
    ["Он сказал, что продаст его мне, если захочу.","He said he would sell it to me if I wanted."],
    ["Он спустился ко мне?","Did he go down to me?"],
    ["Он хотел, чтобы я пришла в десять часов, но я не могла.","He wanted me to come at ten o'clock but I couldn't."],
    ["Она едет на лифте на четвертый этаж.","She takes the lift to the fourth floor."],
    ["Она заканчивает работу и начинает читать журнал.","She finishes her work and starts reading a magazine."],
    ["Она уйдет со мной.","She will go away with me."],
    ["Они всегда опаздывают.","They are always late."],
    ["Они начали разговаривать о новости.","They began to talk about the news."],
    ["Они не будут надеяться на меня.","They will not hope for me."],
    ["Они не любят делать покупки в субботу.","They don't like shopping on Saturdays."],
    ["Осталось только пять минут.","There are only five minutes left."],
    ["Отвезите меня по этому адресу.","Take me to this address."],
    ["По дороге Дэвид остановился, чтобы купить вина.","On the way, David stopped to buy some wine."],
    ["Поеду на своей машине.","I'll take my car."],
    ["Позволь ему пойти.","Let him go."],
    ["Позвольте мне помочь вам.","Let me help you."],
    ["Попросите его перезвонить мне позже.","Ask him to call me back later."],
    ["Почему ты всегда опаздываешь на работу?","Why do you always late for work?"],
    ["Почему я не увижу тебя?","Why will I not see you?"],
    ["Правильно ли я целуюсь?","Am I kissing right?"],
    ["Проверь это и посмотри, не сделал ли я ошибку.","Check this and see if I have made a mistake."],
    ["Сахар возле твоей руки.","The sugar is near your hand."],
    ["Сколько времени ехать на такси от отеля до аэропорта?","How long does it take by taxi from the hotel to the airport?"],
    ["Сколько времени нужно, чтобы получить паспорт?","How long does it take to get a passport?"],
    ["Сколько стоит iphone?","How much is the iphone?"],
    ["Слишком большое движение.","There is too much traffic."],
    ["Слишком много людей.","There are too many people."],
    ["Старые люди, известные как 'граждане сеньоры', получают пенсию.","Old people, known as 'senior citizens', receive pensions."],
    ["Ты долго был в Париже в прошлом году?","How long you were in Paris last year?"],
    ["Ты должен был забронировать комнату раньше.","You should have booked the room earlier."],
    ["Ты должен научиться ходить, прежде чем сможешь бегать.","You must learn to walk before you can run."],
    ["Ты не прав, сегодня двадцать пятое, а не двадцать шестое.","You're wrong, today is the twenty-fifth and not the twenty-sixth."],
    ["Ты собираешься полететь на самолете или поехать на поезде?","Are you going to take a plane or train?"],
    ["Ты хочешь, чтобы я заехал и захватил тебя?","Do you want me to come and pick you up?"],
    ["Увидимся с тобой завтра вечером в половине восьмого.","We'll see you tomorrow night at half-past seven."],
    ["У меня совсем немного денег, чтобы ехать на такси.","I have а little money to take a taxi."],
    ["У тебя будут проблемы.","You will have problems."],
    ["Чем больше я узнаю животных, тем меньше я люблю людей.","The more I know animals the less I love people."],
    ["Что бы ты сделал, если б у тебя было много денег?","What would you do if you had a lot of money?"],
    ["Эта вещь уже недоступна.","This item is no longer available."],
    ["Эта роль была сыграна Джоном.","This role was played by John."],
    ["Это должно быть закончено до следующей недели.","It should be finished by next week."],
    ["Я бы пришла, если ты бы попросил меня.","I would came, if you asked me."],
    ["Я бы хотел столик около окна.","I'd like a table near the window."],
    ["Я езжу на метро каждое утро.","I take the tube every morning."],
    ["Я здесь 2 дня.","I've been here for two days."],
    ["Я знаю его с апреля.","I have known him since April."],
    ["Я надеюсь, что он будет в состоянии получить для меня какую-то информацию.","I hope he will be able to get some information for me."],
    ["Я не буду стараться помочь ему.","I will not try to help him."],
    ["Я не знала его очень долго.","I haven't known him for very long."],
    ["Я не знаю, нужно ли мне пойти.","I don’t know if I should go."],
    ["Я не понимаю, почему он ушел так рано.","I can't understand why he left so early."],
    ["Я никогда не был в Англии.","I have never been to England."],
    ["Я проработал в офисе 4 года.","I worked in an office for four years."],
    ["Я смотрел телевизор, когда пришли мои друзья.","I was watching TV when my friends arrived."],
    ["Я собираюсь купить ту рубашку.","I am going to buy that shirt."],
    ["Я у него спрошу в следующий раз, когда его увижу.","I will ask him the next time I see him."],
    ["Я уже прочитал эту книгу.","I have read this book already"],
    ["Я уже это видел.","I've already seen it."],
    ["Я умею играть в волейбол.","I can play volleyball."],
    ["Я хожу на работу в семь утра.","I go to work at seven in the morning."],
    ["Я хочу что-то важное тебе сказать.","I have something important to tell you."],
    ["Я хочу, чтобы ты пошёл.","I want you to go."],
    ["Я это купил бы.","I would buy it."]];

// послелоги
var test7Data = [["get down","опускаться"],
    ["go around","обходить вокруг"],
    ["go away","уходить"],
    ["go back","возвращаться"],
    ["go by","проходить мимо"],
    ["go out","выходить"],
    ["go up","подниматься"],
    ["look after","присматривать"],
    ["look away","отвернуться"],
    ["look back","оглянуться"],
    ["look out","выглядывать"],
    ["put off","откладывать"],
    ["run away","убегать"],
    ["run out","выбегать"],
    ["switch off","выключить"],
    ["switch on","включить"],
    ["take away","забрать"],
    ["take back","отдать"],
    ["take in","внести"],
    ["take up","поднять"]];